name: GitHub Readme Stats
on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente pelo botão "Run workflow"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats Card
        uses: readme-stats/github-readme-stats-action@v1 # <--- NOME CORRETO
        with:
          gh_token: ${{ secrets.PAT_TOKEN }}
          user: Miki000000
          theme: dracula
          show-icons: true
          count-private: true
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update stats images" || exit 0
          git push
